[[RTCB]]
arch = "i686"
git-tree-sha1 = "f7bbf32c6d3b33e89b2ad56a115d29a6776d4afe"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "cc598085c51923dee71fb9d722fc00df1623d66a39e7bec1ec6959b45698c7d6"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.i686-linux-gnu-libgfortran3.tar.gz"
[[RTCB]]
arch = "i686"
git-tree-sha1 = "164c696737d7e7845b07d76a9b91373276a0d4ac"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "a974a1d250191a152015e0d790ee079bd78af0f326362feb208c1373d1741613"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.i686-linux-gnu-libgfortran4.tar.gz"
[[RTCB]]
arch = "i686"
git-tree-sha1 = "740dddb0f958d9926c3ca44d5a1bb2f545dbbba3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "4361f85c2957c2b491c7ae9be5519702c3ccf7c05c7ca2a566582b018a4b854f"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.i686-linux-gnu-libgfortran5.tar.gz"
[[RTCB]]
arch = "i686"
git-tree-sha1 = "ef3fd3d012f39b1da969a6eba603b9f489e5ff7d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "91d7a910fb1731897e5659a934033ccf90627938c8e33400ee6202eb347655df"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.i686-linux-musl-libgfortran3.tar.gz"
[[RTCB]]
arch = "i686"
git-tree-sha1 = "fc73dc4af6746095b71cefccb7299c9c7c98117c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "3fe94c0c936ada20639034413d2d07cbeca590535be60ede7203dad10d8a1d66"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.i686-linux-musl-libgfortran4.tar.gz"
[[RTCB]]
arch = "i686"
git-tree-sha1 = "dfcefab5aca074560d4c4a2b684a579658f8ca42"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "aa878d4c0745ae30b3cd9b2fcdfbb48cba8ef80c840d83b46c1b36b868fcde76"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.i686-linux-musl-libgfortran5.tar.gz"
[[RTCB]]
arch = "x86_64"
git-tree-sha1 = "808cb9b6c7f091a512fe9f548cd0b8b20cdccc62"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "8e518f0ee6d36b75e84071e52ec34ca8a1fc1347a2594d8ee8de4238c6bdcda7"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[RTCB]]
arch = "x86_64"
git-tree-sha1 = "2d95715ab77f969e13b7e9812d001f74a11a7926"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "acc197256039682cdbe0962cf8b911f625b76e099f00e4d0a30b86f9186e0725"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[RTCB]]
arch = "x86_64"
git-tree-sha1 = "7d3e364f9e2307d4500ce9a79752007f957cc349"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "c3ac578829802d310b89c15ddc2a8c9c02b34585e8665f44a310a8c8c8a6f9a4"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[RTCB]]
arch = "x86_64"
git-tree-sha1 = "a15069a108adaffee448a5b14106145554bcff8b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "8d86319677f55e6a924ff7c82348bb55a77a11987d8ee25d2dc8f0e5e879a075"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[RTCB]]
arch = "x86_64"
git-tree-sha1 = "72905cef426c6b2a1f5b47bcc79651a76f223148"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "8cb90db22b52e951e6ce53d29ffe7c72761bc2f61d8ffff05a22027c2ef4099d"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[RTCB]]
arch = "x86_64"
git-tree-sha1 = "250c16a351dfb60b67226ba335365589c03009de"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[RTCB.download]]
    sha256 = "0dff11b16a9781633028b0c576bfc5dc9bf7df75962f84059f97e26ea6c03c5a"
    url = "https://github.com/JuliaBinaryWrappers/RTCB_jll.jl/releases/download/RTCB-v0.91.0+0/RTCB.v0.91.0.x86_64-linux-musl-libgfortran5.tar.gz"
